const ENDPOINTS = {
    'HOME' : '/',
    'QUESTION_PAGE' : '/question',
    'IDENTITY_PAGE' : '/identity',
    'BACKEND_URL': 'http://localhost:1337/api/'
};

ENDPOINTS.GET_ALL_QUESTION_DOCIDS = `${ENDPOINTS.BACKEND_URL}question-api/all`;
ENDPOINTS.GET_QUESTION_PER_DOCID = `${ENDPOINTS.BACKEND_URL}question-api/docId?documentId=`;
ENDPOINTS.GET_ALL_CHARACTER_DOCIDS = `${ENDPOINTS.BACKEND_URL}identity/all`;
ENDPOINTS.GET_CHARACTER_PER_DOCID = `${ENDPOINTS.BACKEND_URL}identity/docId?documentId=`;
ENDPOINTS.GET_ALL_CATEGORIES = `${ENDPOINTS.BACKEND_URL}character-categories`;
ENDPOINTS.GET_ALL_PLANETS = `${ENDPOINTS.BACKEND_URL}planets`;
ENDPOINTS.GET_ALL_SPECIES = `${ENDPOINTS.BACKEND_URL}species`;
ENDPOINTS.GET_ALL_ALLEGIANCES = `${ENDPOINTS.BACKEND_URL}allegiances`;

Object.freeze(ENDPOINTS);
export default ENDPOINTS;