# .github/workflows/deploy.yml
name: Deploy React App (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install
      run: npm ci --legacy-peer-deps
      
    - name: Build
      run: npm run build --if-present

    - name: Upload production build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-build
        path: build/
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: game-build
          path: ./build
          
      - name: Deploy to server
        run: |
            rsync -avz --delete ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_ADDRESS }}:/sites/game/
